"""added email to user, user_id to answers

Revision ID: 35ebe0e2ddcc
Revises: 40e53cfbdfef
Create Date: 2023-04-05 21:59:01.744304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ebe0e2ddcc'
down_revision = '40e53cfbdfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_answers_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('answers_user_id_foreign_key', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_answers_user_id'))
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
