"""added lesson word

Revision ID: ae135ea07c74
Revises: c1208f474a58
Create Date: 2023-04-10 14:56:59.480238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae135ea07c74'
down_revision = 'c1208f474a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_word_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_word_word_id'), ['word_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_word_word_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_word_user_id'))

    op.drop_table('lesson_word')
    # ### end Alembic commands ###
